md = {
"integrator"            :  ['md','leap-frog integrator'],
"nsteps"                :  ['500000','2 * 500000 = 1000 ps (1 ns)'],
"dt"                    :  ['0.002','2 fs'],
"nstxout"               :  ['0','suppress bulky .trr file by specifying'],
"nstvout"               :  ['0','0 for output frequency of nstxout,'],
"nstfout"               :  ['0','nstvout, and nstfout'],
"nstenergy"             :  ['5000','save energies every 10.0 ps'],
"nstlog"                :  ['5000','update log file every 10.0 ps'],
"nstxout-compressed"    :  ['5000','save compressed coordinates every 10.0 ps'],
"compressed-x-grps"     :  ['System','save the whole system'],
"continuation"          :  ['yes','Restarting after NPT'],
"constraint_algorithm"  :  ['lincs','holonomic constraints'],
"constraints"           :  ['h-bonds','bonds involving H are constrained'],
"lincs_iter"            :  ['1','accuracy of LINCS'],
"lincs_order"           :  ['4','also related to accuracy'],
"rcoulomb"              :  ['1.0','short-range electrostatic cutoff (in nm)'],
"rvdw"                  :  ['1.0','short-range van der Waals cutoff (in nm)'],
"coulombtype"           :  ['PME','Particle Mesh Ewald for long-range electrostatics'],
"pme_order"             :  ['4','cubic interpolation'],
"fourierspacing"        :  ['0.16','grid spacing for FFT'],
"tcoupl"                :  ['V-rescale','modified Berendsen thermostat'],
"tc-grps"               :  ['Protein Water_and_ions','two coupling groups - more accurate'],
"tau_t"                 :  ['0.1 0.1','time constant, in ps'],
"ref_t"                 :  ['300 300','reference temperature, one for each group, in K'],
"pcoupl"                :  ['Parrinello-Rahman','Pressure coupling on in NPT'],
"pcoupltype"            :  ['isotropic','uniform scaling of box vectors'],
"tau_p"                 :  ['2.0','time constant, in ps'],
"ref_p"                 :  ['1.0','reference pressure, in bar'],
"compressibility"       :  ['4.5e-5','isothermal compressibility of water, bar^-1'],
"pbc"                   :  ['xyz','3-D PBC'],
"DispCorr"              :  ['EnerPres','account for cut-off vdW scheme'],
"gen_vel"               :  ['no','Velocity generation is off'],
}

nvt = {
"define"                :  ['-DPOSRES','position restrain the protein'],
"nstxout"               :  ['0','suppress bulky .trr file by specifying'],
"nstvout"               :  ['0','0 for output frequency of nstxout,'],
"nstfout"               :  ['0','nstvout, and nstfout'],
"integrator"            :  ['md','leap-frog integrator'],
"nsteps"                :  ['100000','2 * 100000 = 200 ps'],
"dt"                    :  ['0.002','2 fs'],
"continuation"          :  ['no','first dynamics run'],
"constraint_algorithm"  :  ['lincs','holonomic constraints'],
"constraints"           :  ['h-bonds','bonds involving H are constrained'],
"lincs_iter"            :  ['1','accuracy of LINCS'],
"lincs_order"           :  ['4','also related to accuracy'],
"cutoff-scheme"         :  ['Verlet','Buffered neighbor searching'],
"rcoulomb"              :  ['1.0','short-range electrostatic cutoff (in nm)'],
"rvdw"                  :  ['1.0','short-range van der Waals cutoff (in nm)'],
"DispCorr"              :  ['EnerPres','account for cut-off vdW scheme'],
"coulombtype"           :  ['PME','Particle Mesh Ewald for long-range electrostatics'],
"pme_order"             :  ['4','cubic interpolation'],
"fourierspacing"        :  ['0.16','grid spacing for FFT'],
"tcoupl"                :  ['V-rescale','modified Berendsen thermostat'],
"tc-grps"               :  ['Protein Water_and_ions','two coupling groups - more accurate'],
"tau_t"                 :  ['0.1 0.1','time constant, in ps'],
"ref_t"                 :  ['300 300','reference temperature, one for each group, in K'],
"pcoupl"                :  ['no','no pressure coupling in NVT'],
"pbc"                   :  ['xyz','3-D PBC'],
"gen_vel"               :  ['yes','assign velocities from Maxwell distribution'],
"gen_temp"              :  ['300','temperature for Maxwell distribution'],
"gen_seed"              :  ['-1','generate a random seed'],
}

npt = {
"define"                :  ['-DPOSRES','position restrain the protein'],
"nstxout"               :  ['0','suppress bulky .trr file by specifying'],
"nstvout"               :  ['0','0 for output frequency of nstxout,'],
"nstfout"               :  ['0','nstvout, and nstfout'],
"integrator"            :  ['md','leap-frog integrator'],
"nsteps"                :  ['100000','2 * 50000 = 100 ps'],
"dt"                    :  ['0.002','2 fs'],
"continuation"          :  ['yes','Restarting after NVT'],
"constraint_algorithm"  :  ['lincs','holonomic constraints'],
"constraints"           :  ['h-bonds','bonds involving H are constrained'],
"lincs_iter"            :  ['1','accuracy of LINCS'],
"lincs_order"           :  ['4','also related to accuracy'],
"cutoff-scheme"         :  ['Verlet','Buffered neighbor searching'],
"rcoulomb"              :  ['1.0','short-range electrostatic cutoff (in nm)'],
"rvdw"                  :  ['1.0','short-range van der Waals cutoff (in nm)'],
"DispCorr"              :  ['EnerPres','account for cut-off vdW scheme'],
"coulombtype"           :  ['PME','Particle Mesh Ewald for long-range electrostatics'],
"pme_order"             :  ['4','cubic interpolation'],
"fourierspacing"        :  ['0.16','grid spacing for FFT'],
"tcoupl"                :  ['V-rescale','modified Berendsen thermostat'],
"tc-grps"               :  ['Protein Water_and_ions','two coupling groups - more accurate'],
"tau_t"                 :  ['0.1 0.1','time constant, in ps'],
"ref_t"                 :  ['300 300','reference temperature, one for each group, in K'],
"pcoupl"                :  ['Parrinello-Rahman','Pressure coupling on in NPT'],
"pcoupltype"            :  ['isotropic','uniform scaling of box vectors'],
"tau_p"                 :  ['2.0','time constant, in ps'],
"ref_p"                 :  ['1.0','reference pressure, in bar'],
"compressibility"       :  ['4.5e-5','isothermal compressibility of water, bar^-1'],
"refcoord_scaling"      :  ['com'],
"pbc"                   :  ['xyz','3-D PBC'],
"gen_vel"               :  ['no','Velocity generation is off'],
}

minim = {
"nstxout"               :  ['0','suppress bulky .trr file by specifying'],
"nstvout"               :  ['0','0 for output frequency of nstxout,'],
"nstfout"               :  ['0','nstvout, and nstfout'],
"integrator"            :  ['steep','Algorithm (steep = steepest descent minimization)'],
"emtol"                 :  ['1000.0','Stop minimization when the maximum force < 1000.0 kJ/mol/nm'],
"emstep"                :  ['0.01','Minimization step size'],
"nsteps"                :  ['50000','Maximum number of (minimization) steps to perform'],
"cutoff-scheme"         :  ['Verlet','Buffered neighbor searching'],
"coulombtype"           :  ['PME','Treatment of long range electrostatic interactions'],
"rcoulomb"              :  ['1.0','Short-range electrostatic cut-off'],
"rvdw"                  :  ['1.0','Short-range Van der Waals cut-off'],
"pbc"                   :  ['xyz','Periodic Boundary Conditions in all 3 dimensions'],
}